[package]
name = "bbox"
version = "0.7.6"
authors = ["Henning Meyer <tutmann@gmail.com>"]

description = "Managing axis aligned 3d Bounding Boxes."
repository = "https://github.com/hmeyer/bbox"
readme = "README.md"
keywords = ["boundingbox", "3d", "csg", "union", "intersection"]
license = "GPL-3.0"

[lib]
name = "bbox"
path = "src/lib.rs"

[dependencies]
nalgebra = "0.14"
alga = "0.5"
num-traits = "0.2"
